services:
  chrono:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/chrono/chrono-dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    # /dev/dri does not exist on macOS Docker; remove or override this on Linux
    # devices:
    #   - /dev/dri:/dev/dri
    environment:
      DISPLAY: host.docker.internal:0